### ISSUE TITLE
Searching with a SMILES yields potentially many results but no clear indication why they are listed

### ISSUE THREAD

**Issue by steinbeck** [Steinbeck-Lab/coconut#116]
If you, for example, search for the SMILES of Jobosic Acid "CCCCCCCCCC(C)CCC(C)C(=O)O" you get the result in the attached image. 
To the use, it is unclear, which one is the exact hit, which ones are superstructures of which the search SMILES is a substructure and whether there are hits that are the result of a similarity search. 

<img width="1051" alt="image" src="https://github.com/Steinbeck-Lab/coconut/assets/107318/55ed3637-03a4-4f0f-b8c1-9d0ad471e028">

**Comment by CS76** [comment]
In the latest release, the results of a SMILES search are sorted by similarity (tanimoto, DESC). Closing this for now. Please create an issue/feature request to update

<img width="1256" alt="Screenshot 2024-08-08 at 13 49 01" src="https://github.com/user-attachments/assets/34e68f2d-65e6-4507-bfb4-b50c860c4fc0">
