### ISSUE TITLE
Please add a Search button to the search page

### ISSUE THREAD

**Issue by sriramkanakam87** [Steinbeck-Lab/coconut#142]
Typing a search phrase in the search box on https://coconut.cheminf.studio/search and then hitting return does not initiate a search. Please fix this or add a search button, like you find on the front page.

**Comment by CS76** [comment]
<img width="1221" alt="Screenshot 2024-08-09 at 12 16 32" src="https://github.com/user-attachments/assets/13adff30-6182-4626-893a-9d35ebf628c1">
