### ISSUE TITLE
Improve species search

### ISSUE THREAD

**Issue by sriramkanakam87** [Steinbeck-Lab/coconut#149]
Searching for a full species name, such as /papaver somniferum/ yields results in the organism search. However, just searching for “papaver” should also give results.

**Comment by CS76** [comment]
<img width="1428" alt="Screenshot 2024-08-10 at 12 47 40" src="https://github.com/user-attachments/assets/fa14ab6d-7edf-469a-a6c4-1bb91784a855">
<img width="1429" alt="Screenshot 2024-08-10 at 12 47 20" src="https://github.com/user-attachments/assets/ba51743b-9ecc-4a85-afe6-02b0a96e1a7e">
