### ISSUE TITLE
Issues - Report and request changes to this page options

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/coconut#151]
Request changes to this page" links point to dev.coconut.np.net and does not load… and the link above it (report this compound) also has some problems.

**Comment by sriramkanakam87** [comment]
<img width="1519" alt="Screenshot 2024-08-11 at 21 46 20" src="https://github.com/user-attachments/assets/9c501fe2-3bad-4ce8-96f3-15b2041febec">
