### ISSUE TITLE
Organism search should yield an organism list

### ISSUE THREAD

**Issue by sriramkanakam87** [Steinbeck-Lab/coconut#153]
At the moment, the organism search yields a list of compounds found in this organism.
That is fine, but having a list of organisms above it (like that badges shown in the organisms section of a compound entry) would be great.

**Comment by CS76** [comment]
<img width="1427" alt="Screenshot 2024-08-11 at 22 31 54" src="https://github.com/user-attachments/assets/9706d677-4019-4791-bd59-6f571766e286">
