### ISSUE TITLE
Species curation

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/coconut#158]
- [ ] Merge spp and spp. to spp.
- [ ] Create - Genus spp. for all species on the platform
- [x] General species terms (typos/casing) curation
<img width="1237" alt="Screenshot 2024-08-12 at 14 58 10" src="https://github.com/user-attachments/assets/57d36940-3ced-4ce5-8fee-5ad852d0cc23">

**Comment by Kohulan** [comment]
Species name that doesn't have IRI these should be flagged.
If there are more than two words as part of a name it should be flagged.
If there are brackets in a name should be flagged
If there are names with two words and second word is capitalized it should be flagged
If there are names with special characters flag

**Comment by sriramkanakam87** [comment]
closed in favour of #312
