### ISSUE TITLE
Include copy button next to representations

### ISSUE THREAD

**Issue by Kohulan** [Steinbeck-Lab/coconut#206]
<img width="775" alt="image" src="https://github.com/user-attachments/assets/cf547ba2-4952-41df-9e03-38c11df1334a">

Currently I can only select the representations and copy It would be great to have a copy button next to the representations

**Comment by CS76** [comment]
<img width="793" alt="Screenshot 2024-08-31 at 16 11 52" src="https://github.com/user-attachments/assets/748e499b-45ba-49e8-a8a4-167134e7f74a">

Added copy to clipboard buttons to representations and same logic can be extended to other places where we would like to offer ctc
