### ISSUE TITLE
Updata compound names containing CHEMBL and SCHEMBL ids

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/coconut#208]
ids / names to map
[chembl.csv](https://github.com/user-attachments/files/16757826/chembl.csv)

**Comment by Kohulan** [comment]
[Archive 2.zip](https://github.com/user-attachments/files/16798979/Archive.2.zip)

**Comment by Kohulan** [comment]
download chembl:

```python
import requests
from concurrent.futures import ThreadPoolExecutor


session = requests.Session()

def process_line(line):
    id, standard_inchi, canonical_smiles, identifier, name_ = line.strip().split("\t")
    res = requests.get(f"https://www.ebi.ac.uk/chembl/api/data/molecule.json?molecule_chembl_id={name_}").json()
    if res['molecules']:
        name = res['molecules'][0].get("pref_name", "No name available")
    else:
        name = "No molecules found"
    if name == None:
            name = "Not available"
    return f"{id}\t{standard_inchi}\t{canonical_smiles}\t{identifier}\t{name_}\t{name}\n"

# Reading input and processing lines in parallel
with open("/Users/kohulanrajan/Downloads/chembl.tsv", "r") as fp, \
     open("/Users/kohulanrajan/Downloads/chembl_name1.tsv", "w") as f_open, \
     ThreadPoolExecutor() as executor:

    # Process lines in parallel
    results = executor.map(process_line, fp)
    
    # Write results to the output file
    for result in results:
        f_open.write(result)
  ```
  
  SureChEMBL
  ```
  import requests
  
  f_open =open("/Users/kohulanrajan/Downloads/scchembl_name.tsv","w")

with open("/Users/kohulanrajan/Downloads/scchembl.tsv","r") as fp:
    
    for i,line in enumerate(fp):
        id,standard_inchi,canonical_smiles,identifier,name_ = line.strip().split("\t")
        res = requests.get(f"https://surechembl.org/api/chemical/id/{name_[7:]}").json()
        name = res["data"][0]["name"]
        f_open.write(id+"\t"+standard_inchi+"\t"+canonical_smiles+"\t"+identifier+"\t"+name_+"\t"+name+"\n")
 ```

**Comment by CS76** [comment]
Missing entries

CHEMBL3352924
CHEMBL4913169
CHEMBL2419113
CHEMBL4786727
CHEMBL3353844
CHEMBL3970351
CHEMBL4942606
CHEMBL3966800
CHEMBL3971446
CHEMBL4556044
CHEMBL517633
CHEMBL4958544
CHEMBL4975868
CHEMBL4923789
CHEMBL1078156
CHEMBL3234600
CHEMBL459070
CHEMBL3352923
CHEMBL113882
CHEMBL4129187
CHEMBL1078062
CHEMBL3234599
CHEMBL1765724
CHEMBL4900852
CHEMBL4891743
CHEMBL3353331
CHEMBL2269291
CHEMBL2391696
CHEMBL1079715
CHEMBL2409144
CHEMBL3980244
CHEMBL2391695
CHEMBL4126392
CHEMBL526383
CHEMBL3353332
CHEMBL4756932
CHEMBL2391537
CHEMBL514407
CHEMBL3353848
CHEMBL1626640
CHEMBL5004963
CHEMBL4956147
CHEMBL1852484
CHEMBL3353333
CHEMBL1079714
CHEMBL3353847
CHEMBL4761157
CHEMBL436384
CHEMBL2036990
CHEMBL2392401
CHEMBL230164
CHEMBL3234601
CHEMBL5020524
CHEMBL3234602
CHEMBL3353850
CHEMBL5201288
CHEMBL5175880
CHEMBL4908241
