### ISSUE TITLE
How to obtain detailed descriptions of various fields in the database?

### ISSUE THREAD

**Issue by mizzlefeng** [Steinbeck-Lab/coconut#234]
I opened the Coconut database using PostgreSQL, which allows me to view more detailed information than the website. And each table contains many fields, many of which are abbreviations. How can I know the meaning of each field?

**Comment by CS76** [comment]
@mizzlefeng Could you please specify which table you are particularly interested in?

Here is the schema: https://www.figma.com/board/yVQeNRsqlkXOgI5BIlMlb4/COCONUT_DB?node-id=0-1&node-type=CANVAS

@sriramkanakam87
Please add column descriptions when it is an abbreviation and not obvious

**Comment by mizzlefeng** [comment]
@CS76 I need to use molecules and properties, which should contain molecular information of all natural products. Can detailed descriptions of the fields of these two tables be given? Although most of the fields can be guessed, they cannot be completely determined. For example, the difference between molecular_weight and exact_molecular_weight in the properties table, I found that the molecular weight displayed on the website is exact_molecular_weight.
In addition, I have two questions about SQL.
1. The website says there are 695,133 molecules, but the molecules table has 1061,258 records and the properties table has 1061,290 records. Why is this?
2. I did not find information about Fsp3 in the properties table.

**Comment by mizzlefeng** [comment]
@CS76 I also found that the formal_charge values ​​in the properties table are all 0, but there are specific values ​​on the website. Why?

**Comment by CS76** [comment]
> I need to use molecules and properties, which should contain molecular information of all natural products. Can detailed descriptions of the fields of these two tables be given? Although most of the fields can be guessed, they cannot be completely determined. For example, the difference between molecular_weight and exact_molecular_weight in the properties table, I found that the molecular weight displayed on the website is exact_molecular_weight.

With regards to exact molecular weight, you could see a small info icon next to the value displayed on the website with details
<img width="666" alt="Screenshot 2024-09-05 at 09 39 35" src="https://github.com/user-attachments/assets/eb608364-499d-472c-8b55-9cd0b27dabd9">

We will also update the schema/docs to reflect all the fields as soon as we can. 
@sriramkanakam87 

> For example, the difference between molecular_weight and exact_molecular_weight in the properties table, I found that the molecular weight displayed on the website is exact_molecular_weight.

exact_molecular_weight is the exact isotopic mass calculated using RDKit

```
ExactMolWt(Chem.MolFromSmiles('CC'))
30.04...

ExactMolWt(Chem.MolFromSmiles('[13CH3]C'))
31.05...
```

> * The website says there are 695,133 molecules, but the molecules table has 1061,258 records 

<img width="374" alt="Screenshot 2024-09-05 at 09 44 36" src="https://github.com/user-attachments/assets/abdc0929-9234-45e9-9c86-28fabff721f2">

PostgreSQL dump is the entire db (active/inactive). We don't delete any molecule records in COCONUT (for traceability); instead, we track all changes in the database while flagging them as active/inactive / parent/variant, etc.

The total records you see in the molecules include parents without any stereo definitions and also revoked entries, etc. We are publishing an update to the coconut paper soon, which should contain all the details. Also, the documentation site should/will have this information (soon). 

> and the properties table has 1061,290 records. Why is this?

If you check the schema, properties are always one-to-one mapped with molecule records, so the difference you find could be soft deletes (not removed during the exports but will be removed in the next round) 

> * I did not find information about Fsp3 in the properties table.

The column you need to look for is the fractioncsp3. Thank you for pointing this out; values on the website are not pointing to the right column. An update will be deployed soon.


> I also found that the formal_charge values ​​in the properties table are all 0, but there are specific values ​​on the website. Why?

I just checked, and they are not always zero. Please sort the column, re-check and confirm.

**Comment by mizzlefeng** [comment]
Thank you for your detailed answer, but I still have two questions.

1. This is the database I restored, and the formal_charge column only has four values: 0, -1, 1, and 2.
![image](https://github.com/user-attachments/assets/2a513f3f-9262-4c22-a7d7-e9f930e9e25b)

2. I guessed that Fsp3 is the fractioncsp3 field, but its values ​​are all between 0 and 1. It seems that it has been normalized? As far as I know, there are specific values ​​on the website.
![image](https://github.com/user-attachments/assets/8e9e94a5-de89-463d-a2dc-e717e9ab2547)
![image](https://github.com/user-attachments/assets/f007285b-0be9-4eb9-950c-ab25bbe4e2b7)

**Comment by CS76** [comment]
1) Regarding the fsp3, as I mentioned, there is a bug in the website code that points Fsp3 values to a different column. This will be fixed soon. Column fractioncsp3 is the correct mapping. Please use it.

For more details:
https://www.rdkit.org/docs/source/rdkit.Chem.Lipinski.html

2) formal_charge: I believe your query is checking with an AND condition with the fractioncsp3. Please remove the additional condition and check if it expands the forma_charge results.
