### ISSUE TITLE
Download page should mention relase notes

### ISSUE THREAD

**Issue by steinbeck** [Steinbeck-Lab/coconut#237]
### Title

Download page should mention release notes

### Description

Currently, it is not apparent to the user how to get informed about changes between releases. It should be mentioned on the download page that release notes are available on Zenodo. It could also be mentioned that Zenodo contains not only previous releases but also current ones, including release notes.

### Potential Benefits

User is better informed

### Priority

Low

### Impact

Happier users and happier group leader

**Comment by CS76** [comment]
<img width="1051" alt="Screenshot 2024-09-11 at 14 36 34" src="https://github.com/user-attachments/assets/7831d7e0-94d1-49a1-a409-433154459112">
