### ISSUE TITLE
Figure in database documentation requires to be logged into Figma

### ISSUE THREAD

**Issue by steinbeck** [Steinbeck-Lab/coconut#238]
### Summary

Figure in database documentation requires to be logged into Figma

### Description

Figure in database documentation on https://steinbeck-lab.github.io/coconut/db-schema.html requires to be logged into Figma. See screenshot.

### Expected Behavior

Figure should show without login

### Actual Behavior

Figure does not show without login

### Steps to Reproduce

Goto that page

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/5b970432-9889-4c7e-8ce1-999139574ab0)

### Environment

Latest Chrome on MacOS Sonoma

**Comment by CS76** [comment]
<img width="1403" alt="Screenshot 2024-09-09 at 10 15 44" src="https://github.com/user-attachments/assets/52481ece-8c55-4178-8c9d-9cbbfa6903ef">
