### ISSUE TITLE
Hope to add "name" in the CSV download format

### ISSUE THREAD

**Issue by JustinYiChen** [Steinbeck-Lab/coconut#248]
### Title

Hope to add "name" in the CSV download format

### Description

Add a "compound name" column in the downloaded CSV format to provide users with a more intuitive reference name.

The request is to include a "compound name" column in the CSV files generated by the system. This would provide users with a clear and direct reference to the compound names, making it easier to identify specific natural products, especially for those unfamiliar with the internal database structure.

### Potential Benefits

This would allow users unfamiliar with the database to quickly find target natural product names in the CSV file.

Including the "name" column would make the data more accessible to a broader audience, enabling users to identify compounds more efficiently. It would also enhance usability for individuals who rely on CSV formats for their data analysis, especially when searching for specific natural products.

### Use Case

In literature review and statistical analysis, the "name" field in the CSV file allows for quick classification and quantification of natural product literature.

For example, researchers conducting statistical analyses on natural product literature could use the "name" column in the CSV file to quickly organize, classify, and perform statistical analysis on the literature data, significantly improving workflow efficiency.

### Priority

High

### Impact

This feature simplifies the process for researchers unfamiliar with SQL or database systems, enabling them to quickly extract all known natural product names without needing to repeatedly access the database.

By providing the "name" in the CSV file, users can bypass the complexity of querying the database directly, saving time and resources, particularly for scholars who are not well-versed in database querying. This enhancement would allow for more streamlined access to natural product data.

### Contact Information

j40322@gmail.com

**Comment by CS76** [comment]
@JustinYiChen, Apparently, the names of many compounds are missing. We could include the IUPAC names, but they need to be standardised. We will update the October release to include additional meta data. Thank you for your feedback.

**Comment by CS76** [comment]
Dear @JustinYiChen, we now have additional exports with a lot of metadata, including names, IUPAC names, etc in our October release.
I hope this helps.

https://coconut.naturalproducts.net/download
