### ISSUE TITLE
Missing data importing the PostgresSQL dump.

### ISSUE THREAD

**Issue by LWdaHustla** [Steinbeck-Lab/coconut#255]
### Summary

After importing the .sql file, certain data seems to be missing and errors occur when executing the script.

### Description

After importing the postgres dump into a existing database connection via pgAdmin, tables like "properties" or "sample_location" have no data in it. 

Furthermore, when executing the script there seem to be a lot of "invalid command" errors.

### Expected Behavior

for example:
- "properties" table should have data as well as "sample_locations"

### Actual Behavior

No data is shown in those tables. The tables themselves do exist though.

### Steps to Reproduce

- download coconut-09-2024.sql
- connect to a postgres database
- import dump via psql: "\i path/to/file/coconut-09-2024.sql'
- look at logs and tables

### Screenshots/Logs

![{7B40B02E-8E35-4A36-906C-31B65F018B2A}](https://github.com/user-attachments/assets/c40aaca2-d97f-4b14-9a12-5a192355f72c)

### Environment

- Operating System: Windows 11
- pgAdmin 4

### Additional Information

The august version still had the information about "properties" for example.

**Comment by CS76** [comment]
@LWdaHustla 

Sample_location information is in the pivot table (check the molecule_organism table's pivot column, organism_parts). We are curating the data further, which will populate the sample_locations table with IRI and other ontology mappings, estimated to be available in the November release.

Please share your restore command so that we can look at the invalid command issue.

**Comment by LWdaHustla** [comment]
@CS76 
Thanks for the reply!

After connecting to my PostgreSQL database, the restore command I used was:
``` bash
\i path/to/file/coconut-09-2024.sql
```

In another attempt, I first created the role **sail**, so the error message "role 'sail' doesn't exist" no longer appears. This error didn't seem to affect anything before, but I resolved it just in case:

```sql
CREATE ROLE sail;
```

After that, the script runs smoothly at first, creating all the correct tables. However, a large number of error messages like the following start to appear:
```bash
6102197: error: invalid command \
6102205: error: invalid command \
6102206: error: invalid command \
6102211: error: invalid command \
```
occurs.

This continues for a few minutes. Afterward, most of the tables and their structure are there, but the main issue remains: the content of the **properties** table, for example, is missing.

I'm still trying to figure out if this issue is on my side. However, if you have any idea why this might be happening or if it's intentional behavior, I'd appreciate your input.

**Comment by CS76** [comment]
@LWdaHustla 

Try using pg_restore

```
PGPASSWORD="${DB_PASSWORD}" pg_restore \
  --username="${DB_USERNAME}" \
  --dbname="${DB_DATABASE}" \
  --no-owner \
  --role="${DB_USERNAME}" \
  --clean \
  --if-exists \
  /path/to/your_backup_file.dump
  ```

**Comment by LWdaHustla** [comment]
@CS76 

With the pg_restore and the new october dump everything works perfectly, thank you very much!
