### ISSUE TITLE
Substructure search for indole just yields the exact hit (sometimes) 

### ISSUE THREAD

**Issue by steinbeck** [Steinbeck-Lab/coconut#52]
Substructure search for indole just yields the exact hit (sometimes). I went to the coconut.cheminf.studio site, clicked on "Draw Structure", drew indole and switched the radio buttons to "substructure search". I only got indole as a result. There are many, many more.

**Comment by CS76** [comment]
<img width="1148" alt="Screenshot 2024-08-07 at 09 06 59" src="https://github.com/user-attachments/assets/e2665528-63c8-4466-a55f-e9c6e45a6845">
<img width="1258" alt="Screenshot 2024-08-07 at 09 07 17" src="https://github.com/user-attachments/assets/f6861046-25cc-434a-a567-8e50e9a434fa">
