### ISSUE TITLE
Identiy, inspect and potentially remove multi-molecule data entries

### ISSUE THREAD

**Issue by steinbeck** [Steinbeck-Lab/coconut#53]
Bug present on coconut.cheminf.studio:
Entries like 
<img width="1294" alt="image" src="https://github.com/Steinbeck-Lab/coconut/assets/107318/397ea2b9-5c74-4bfb-b7cc-48dfb1a3d3fd">
(CNP0588739) with two distinct molecules should be identified. Cases where the other molecule(s) is/are not counter ions should be removed.

**Comment by CS76** [comment]
Entries from the following list are now deactivated / revoked - https://cloud.uni-jena.de/s/emrM7NRJBw3QaqD

**Comment by CS76** [comment]
<img width="1274" alt="Screenshot 2024-08-07 at 09 09 45" src="https://github.com/user-attachments/assets/350067f4-35c3-4fdf-8731-d83f3abde89b">
