### ISSUE TITLE
Lotus style organism details display

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/coconut#84]
Display organism details just like how lotus displays on its website

- [ ] Reimport data
- [ ] Store the data as JSON
- [ ] Create views to enable rich view

<img width="922" alt="Screenshot 2024-06-26 at 13 41 27" src="https://github.com/Steinbeck-Lab/coconut/assets/4065285/828b58bb-6225-41b3-8790-3e294e293f83">

**Comment by sriramkanakam87** [comment]
closing in favour of #312
